### ISSUE TITLE
node_modules в репозитории

### ISSUE THREAD

**Issue by SanyaPilot** [VovaDVA/joint#134]
Ало ребята, какие node_modules в репозитории?)))0 Вы insights посмотрите, у вас там счет добавлений идет на сотни тысяч, уберите этот пиздец)
![изображение](https://github.com/VovaDVA/joint/assets/29630471/367cc755-24aa-43ea-9638-8e8281b23680)
![изображение](https://github.com/VovaDVA/joint/assets/29630471/6832fad6-c430-4627-af16-358122e8cfc7)

**Comment by SanyaPilot** [comment]
Люди в добром здравии такое не пушат...

**Comment by VovaDVA** [comment]
Так надо))

**Comment by SanyaPilot** [comment]
@VovaDVA это ужас

**Comment by Aleksio02** [comment]
Омайгад, вы что, crazy?)

**Comment by Sergey001k** [comment]
Вова, а я тебе говорил!
